imitation_objective:
  _target_: nuplan.planning.training.modeling.objectives.safe_trajectory_weight_decay_imitation_objective.SafeTrajectoryWeightDecayImitationObjective
  _convert_: 'all'

  weight: 1.0                  # weight contribution to the overall loss
