hydra:
  # run:
  #   dir: ${output_dir}
  # output_subdir: ${output_dir}/code/hydra           # Store hydra's config breakdown here for debugging
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://nuplan.planning.script.config.training
    - pkg://nuplan.planning.script.config.simulation
    - pkg://nuplan.planning.script.config.nuboard
    
    - pkg://nuplan.planning.script.config.common
    - pkg://nuplan.planning.script.experiments

defaults:
  - default_training
  # - default_simulation
  # - default_nuboard

  # - override /+training: training_vector_model

  - override /objective:
    - imitation_objective
  - override /splitter: nuplan
  - override /training_metric:
      - avg_displacement_error
      - avg_heading_error
      - final_displacement_error
      - final_heading_error


tasks: [train] # [train, simulate, open_nuboard]

## TRAINING
config_path_training: ../nuplan/planning/script/config/training # Location of path with all training configs
config_name_training: default_training # default = default_training & default_simulation
config_path_simulation: ../nuplan/planning/script/config/simulation # Location of path with all training configs
config_name_simulation: default_simulation # default = default_training & default_simulation
config_path_nuboard: ../nuplan/planning/script/config/nuboard # Location of path with all training configs
config_name_nuboard: default_nuboard # default = default_training & default_simulation
# save_dir = $NUPLAN_EXP_ROOT

# Name of the experiment
experiment: vector_experiment
model: vector_model
training_model: training_vector_model
lr_scheduler: multistep_lr
# - override /model: vector_model multistep_lr.milestones: [5, 10]  # would need to load cfg file with hydra to override

# Training params
py_func: train # [train, test, cache]
scenario_builder: nuplan # [nuplan, nuplan_challenge, nuplan_mini]
limit_total_scenarios: 500
max_epochs: 2
batch_size: 8
lightning_accelerator: ddp_spawn
num_workers: 8

## SIMULATION
# ego_controller: perfect_tracking_controller   # already set with challenge
# observation: box_observation                  # already set with challenge
# Select the planner and simulation challenge
planner: ml_planner  # [simple_planner, ml_planner]
challenge: open_loop_boxes  # [open_loop_boxes, closed_loop_nonreactive_agents, closed_loop_reactive_agents]
scenarios: all_scenarios # [all_scenarios, nuplan_challenge_scenarios, one_continuous_log, one_of_each_scenario_type] # initially select all scenarios in the database
# scenario_types: [near_multiple_vehicles,
#                  on_pickup_dropoff,
#                  starting_unprotected_cross_turn,
#                  high_magnitude_jerk]
scenario_types: [
                # starting_straight_traffic_light_intersection_traversal,
                 high_lateral_acceleration,
                #  changing_lane,
                #  high_magnitude_speed,
                #  low_magnitude_speed,
                #  starting_left_turn,
                #  starting_right_turn,
                #  stopping_with_lead,
                #  following_lane_with_lead,
                #  near_multiple_vehicles,
                #  traversing_pickup_dropoff,
                #  behind_long_vehicle,
                #  waiting_for_pedestrian_to_cross,
                #  stationary_in_traffic
                 ]
# all_scenarios = ['accelerating_at_crosswalk', 'accelerating_at_stop_sign', 'accelerating_at_stop_sign_no_crosswalk', 'accelerating_at_traffic_light', 'accelerating_at_traffic_light_with_lead', 'accelerating_at_traffic_light_without_lead', 'behind_bike', 'behind_long_vehicle', 'behind_pedestrian_on_driveable', 'behind_pedestrian_on_pickup_dropoff', 'changing_lane', 'changing_lane_to_left', 'changing_lane_to_right', 'changing_lane_with_lead', 'changing_lane_with_trail', 'crossed_by_bike', 'crossed_by_vehicle', 'following_lane_with_lead', 'following_lane_with_slow_lead', 'following_lane_without_lead', 'high_lateral_acceleration', 'high_magnitude_jerk', 'high_magnitude_speed', 'low_magnitude_speed', 'medium_magnitude_speed', 'near_barrier_on_driveable', 'near_construction_zone_sign', 'near_high_speed_vehicle', 'near_long_vehicle', 'near_multiple_bikes', 'near_multiple_pedestrians', 'near_multiple_vehicles', 'near_pedestrian_at_pickup_dropoff', 'near_pedestrian_on_crosswalk', 'near_pedestrian_on_crosswalk_with_ego', 'near_trafficcone_on_driveable', 'on_all_way_stop_intersection', 'on_carpark', 'on_intersection', 'on_pickup_dropoff', 'on_stopline_crosswalk', 'on_stopline_stop_sign', 'on_stopline_traffic_light', 'on_traffic_light_intersection', 'starting_high_speed_turn', 'starting_left_turn', 'starting_low_speed_turn', 'starting_protected_cross_turn', 'starting_protected_noncross_turn', 'starting_right_turn', 'starting_straight_stop_sign_intersection_traversal', 'starting_straight_traffic_light_intersection_traversal', 'starting_u_turn', 'starting_unprotected_cross_turn', 'starting_unprotected_noncross_turn', 'stationary', 'stationary_at_crosswalk', 'stationary_at_traffic_light_with_lead', 'stationary_at_traffic_light_without_lead', 'stationary_in_traffic', 'stopping_at_crosswalk', 'stopping_at_stop_sign_no_crosswalk', 'stopping_at_stop_sign_with_lead', 'stopping_at_stop_sign_without_lead', 'stopping_at_traffic_light_with_lead', 'stopping_at_traffic_light_without_lead', 'stopping_with_lead', 'traversing_crosswalk', 'traversing_intersection', 'traversing_narrow_lane', 'traversing_pickup_dropoff', 'traversing_traffic_light_intersection', 'waiting_for_pedestrian_to_cross'] # all 73 scenario types
scenarios_per_type: 2 # use 10 scenarios per scenario type

# possibly add these
# "scenario_filter.log_names=['2021.06.23.16.54.19_veh-35_00808_01256']",
# 'scenario_filter.limit_total_scenarios=2',  # use 2 total scenarios
# """selected_simulation_metrics='[ego_acceleration_statistics, ego_jerk_statistics]'""",

# to access env var from cfg
# ${oc.env:NUPLAN_EXP_ROOT}/exp

# to access cfg var from cfg
# training_model: training_${model}