_target_: nuplan.planning.training.modeling.models.urban_driver_closed_loop_with_v_model.UrbanDriverClosedLoopModel
_convert_: 'all'

# Model setup
# Internal model parameters
model_params:
  _target_: nuplan.planning.training.modeling.models.urban_driver_closed_loop_with_v_model.UrbanDriverClosedLoopModelParams
  _convert_: 'all'
  local_embedding_size: 256
  global_embedding_size: 256
  num_subgraph_layers: 3
  global_head_dropout: 0.0
  ## Closed-loop specific properties
  detach_unroll: True # if to detach between steps when training with unroll
  warmup_num_frames: 10 # "sample" warmup_num_steps by following the model's policy
  discount_factor: 0.8 # discount future timesteps via discount_factor**t
  limit_predicted_yaw: True

  draw_visualizations: False
  current_task: null  # for the model to know that it is in training or simulation mode
  log_dir: ${oc.env:NUPLAN_EXP_ROOT}/training/urban_driver_closed_loop_with_v_experiment/urban_driver_closed_loop_with_v_model
  checkpoint_dir: ${oc.env:NUPLAN_EXP_ROOT}/training/urban_driver_closed_loop_with_v_experiment

# Params for features
feature_params:
  _target_: nuplan.planning.training.modeling.models.urban_driver_closed_loop_with_v_model.UrbanDriverClosedLoopModelFeatureParams
  _convert_: 'all'
  feature_types:
    NONE: -1
    EGO: 0
    VEHICLE: 1
    BICYCLE: 2
    PEDESTRIAN: 3
    LANE: 4
    STOP_LINE: 5
    CROSSWALK: 6
    LEFT_BOUNDARY: 7
    RIGHT_BOUNDARY: 8
    ROUTE_LANES: 9
  total_max_points: 16
  past_time_steps: 4
  future_time_steps: 16   # 20
  feature_dimension: 6    # 8, 3
  history_num_frames_ego: 4      # <= past_time_steps
  history_num_frames_agents: 4   # <= past_time_steps
  # Agent features
  agent_features: [VEHICLE, BICYCLE, PEDESTRIAN] # [VEHICLE, BICYCLE, PEDESTRIAN]
  ego_dimension: 5        # 8, 3
  agent_dimension: 6      # 8
  max_agents: 30

  past_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 4      # target future poses
    time_horizon: 1.5  # [s] time horizon of future poses
  # Map features
  map_features: [LANE, LEFT_BOUNDARY, RIGHT_BOUNDARY, STOP_LINE, CROSSWALK, ROUTE_LANES]
  max_elements:
    LANE: 30
    LEFT_BOUNDARY: 30
    RIGHT_BOUNDARY: 30
    STOP_LINE: 20
    CROSSWALK: 20
    ROUTE_LANES: 30
  max_points:
    LANE: 20
    LEFT_BOUNDARY: 20
    RIGHT_BOUNDARY: 20
    STOP_LINE: 20
    CROSSWALK: 20
    ROUTE_LANES: 20
  vector_set_map_feature_radius: 35    # [m] The query radius scope relative to the current ego-pose.
  interpolation_method: linear
  disable_map: False
  disable_agents: False
# Params for targets
target_params:
  _target_: nuplan.planning.training.modeling.models.urban_driver_closed_loop_with_v_model.UrbanDriverClosedLoopModelTargetParams
  _convert_: 'all'
  num_output_features: 6 # 48, 3
  # Parameters for predicted trajectory
  future_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 16      # target future poses
    time_horizon: 8.0  # [s] time horizon of future poses
  expert_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 20      # target future poses
    time_horizon: 10.0  # [s] time horizon of future poses
