_target_: nuplan.planning.training.modeling.models.urban_autobot_model.UrbanAutoBotModel
_convert_: 'all'

# Model setup
# Internal model parameters
model_params:
  _target_: nuplan.planning.training.modeling.models.urban_autobot_model.UrbanAutoBotModelParams
  _convert_: 'all'
  # local_embedding_size: 256
  # global_embedding_size: 256
  # num_subgraph_layers: 3
  # global_head_dropout: 0.0
  d_k: 128 # hidden_size
  _M: 100 # num_other_agents
  c: 6 # num_modes
  T: 16
  L_enc: 4
  dropout: 0.1
  k_attr: 2
  map_attr: 3
  num_heads: 16
  L_dec: 4
  tx_hidden_size: 384
  use_map_img: False
  use_map_lanes: True # False
# Params for features
feature_params:
  _target_: nuplan.planning.training.modeling.models.urban_autobot_model.UrbanAutoBotModelFeatureParams
  _convert_: 'all'
  feature_types:
    NONE: -1
    EGO: 0
    VEHICLE: 1
    BICYCLE: 2
    PEDESTRIAN: 3
    LANE: 4
    STOP_LINE: 5
    CROSSWALK: 6
    LEFT_BOUNDARY: 7
    RIGHT_BOUNDARY: 8
    ROUTE_LANES: 9
  total_max_points: 5 # 20
  feature_dimension: 8
  # Agent features
  agent_features: [VEHICLE]
  ego_dimension: 3
  agent_dimension: 8
  max_agents: 100 # 30
  past_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 4      # target future poses
    time_horizon: 1.5  # [s] time horizon of future poses
  # Map features
  map_features: [LANE, LEFT_BOUNDARY, RIGHT_BOUNDARY, STOP_LINE, CROSSWALK, ROUTE_LANES]
  max_elements:
    LANE: 30
    LEFT_BOUNDARY: 30
    RIGHT_BOUNDARY: 30
    STOP_LINE: 20
    CROSSWALK: 20
    ROUTE_LANES: 30
  max_points:
    LANE: 20
    LEFT_BOUNDARY: 20
    RIGHT_BOUNDARY: 20
    STOP_LINE: 20
    CROSSWALK: 20
    ROUTE_LANES: 20
  vector_set_map_feature_radius: 35    # [m] The query radius scope relative to the current ego-pose.
  interpolation_method: linear
  disable_map: False
  disable_agents: False
# Params for targets
target_params:
  _target_: nuplan.planning.training.modeling.models.urban_autobot_model.UrbanAutoBotModelTargetParams
  _convert_: 'all'
  num_output_features: 48
  # Parameters for predicted trajectory
  future_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 16      # target future poses
    time_horizon: 8.0  # [s] time horizon of future poses
